### PR TITLE
Quitesome fixes and new features

### PR DESCRIPTION
**Pull request by Thomas-A-Reinert**
- Aria improvements and deletion of redundant role-attributes.
- Enhanced next/previous links in post.
- Numbered navigation on index/blog/archive pages.
- Support for left/right sidebar and fullwidth/fixedwidth settings on all pages now.
- Hero slider template for single pages. See #125
- Improved 404 page template. Deleted hardcoded widgets, replaced by its own widget-area.
- Added separator between "posted on" date and "updated" date.
- Translation for "in" on author.php. See #107 
- Remove "chrome=1" from X-UA-Compatible. Didn´t validate.

### CODE REVIEW

**Comment by holger1411** [comment]
Seems we had a lot of merge conflicts here. I commit a fix for the left/right/both sidebars layout yesterday.
Seems we´ve done of the same stuff at the same time;-)

**Comment by holger1411** [comment]
The gallery code is also a duplicate.
I´am not a Github/Git pro ... can´t find a way here to cherrypick certain commits. Anyone an idea?

**Comment by saknopper** [comment]
It probably needs a rebase by the author. The PR will pick that up automatically.

**Comment by Thomas-A-Reinert** [comment]
Sorry for various conflicts, also NOT a github pro, so please bear with me. Does anyone know a best-practice tutorial on how to work with forks and committing to the original repo?

And yes, the gallery was just a quick copy and paste to my setup as I saw it was submitted. Probably not the best way to manage it :/

Anyway, hope you enjoy the outcome.

**Comment by holger1411** [comment]
@Thomas-A-Reinert: No problem! Its my first open source project here on GitHub, still trying to find out the best way to manage it...will dig into it.

**Comment by stef-k** [comment]
@Thomas-A-Reinert, @holger1411  sorry for the late response, 

here is a very good and simple guide on how to contribute to open source projects using git and github

http://blog.davidecoppola.com/2016/11/howto-contribute-to-open-source-project-on-github/

hope it helps a bit

**Comment by Thomas-A-Reinert** [comment]
hey @stef-k thank you first of all. I´m just able to care about understrap in my spare/free time, so thats not until friday to monday.

anyway, i´m glad about any info on how to improve the workflow. It SEEMS to me that NONE of my aria improvements as well as the other deflicts have been taken into account with the latest release. Even if they would fix some validator/aria problems. I´m cool, we can do that anytime later...

Don´t t get me wrong: I´m not pissed about it. But in some other case of view, i am, because i put pretty much time into it. As well as the desired "hero-slider-on-pages-plugin".. ;)

For example: I cant see that nor any of the Aria-Improvements on the latest publishing tree.. And I wonder why. This may be the thing that holger meant with "cherry picking" - merge certain improvements of a pull request while neglecting other ones.

**Comment by Thomas-A-Reinert** [comment]
I am always willing to learn. Really.  So if you got any mentionable tuts, í´m willing to apply. Still gotta learn a LOT. And PLEASE go hard on me if you don´t see any kind of progress. Just give me a RTFM, and I´m fine.!

**Comment by holger1411** [comment]
@Thomas-A-Reinert No problem, its the same here. Sometimes Ive got an hrs here or there to work on it, but basically its a spare time project.

Maybe we should start a CONTRIBUTE.md file with some rules to contribute ;-)
But basically:
- commit early and commit often
- One new featuere or one bugfix per PR

I will merge most of your smaller changes manually and some changes are obsolet. Will add infos here. Maybe you could run a pull request for the rest after it?

**Comment by holger1411** [comment]
What ive done manually:
https://github.com/holger1411/understrap/pull/128/commits/c9265585cbdc7557800db547ba92b206f9fcfe10

https://github.com/holger1411/understrap/pull/128/commits/faab7b623d33cb463f6b2971ed26979459f360c9

https://github.com/holger1411/understrap/pull/128/commits/db8a70bb8731a050f21e569844988615c9d7a74a

https://github.com/holger1411/understrap/pull/128/commits/313856578b7e3b00942257f8e8eb31a024324d7d

https://github.com/holger1411/understrap/pull/128/commits/df569b6a0a3a884d1c9d8b5316995d6949b955eb

https://github.com/holger1411/understrap/pull/128/commits/93efd878fe39aa22da6b9d4c7bf9885cf1aa108a

https://github.com/holger1411/understrap/pull/128/commits/5dad8aa25deb57aaad73a95cadacfa007b00a168

What ive not added (because its more complex):
 	Add support for page hero slider
 	Add widget area to 404 page
 	Improve article-pagination
 	Embed numbered pagination for index/blog and archives.
 	Update: increased margin for bottom navigation.
        Add clearfix to avoid mixing with comments

@Thomas-A-Reinert : I can do this manually, too.

**Comment by stef-k** [comment]
@Thomas-A-Reinert about tutorials, [treehouse has many series about wp both for administrating and development](https://teamtreehouse.com/library/topic:wordpress) which  I've found many of them very helpful.

its a paid subscription sevice but they offer 7 days free access. I tried to do the most important during that time which it helped me to jumpstart  into wp dev.

I am not affiliated with them, just a happy customer...

**Comment by Thomas-A-Reinert** [comment]
Hey, @stef-k sorry for getting back so late. I´m superbusy atm, so please bear with me. Big companies are trying to fully spend their budget late that year. With Drupal installs though at a 20:1 ratio vs. Wordpress, with which i´m not comfi at all (yet). So i´m having a 12-16hrs day spending on drupal installs atm. *Sigh*

Thanks very much for the hint bout the tuts, i´ll try to work through them once I find the time to do so. really wanna try to contribute without any conflicts and getting that stuff (mine at least) more productive. so @holger1411 - sorry, really. Thanks for taking my additions into account though and adding them MANUALLY :+1:

**Comment by holger1411** [comment]
Closing this because it is outdated or was already implemented

**Pull request closed without merging**
