### PR TITLE
Organize sidebar files into loop-templates directory

### PR DESCRIPTION
**Pull request by axlright**
Based on issue #708, moved sidebar files into `loop-templates` directory. Deleted sidebar.php as no files actively referenced it (and it had old markup). Made two other minor closing div comment changes.

### CODE REVIEW

**Comment by Thomas-A-Reinert** [comment]
Hi Alex, don´t want to be "über-correct", but the sidebars are not really LOOP-Templates, are they? So I think they´re kinda misplaced in the loop-templates dir.

I´d suggest putting them in the global-templates dir or into a new sidebar-templates dir, what do you think?

**Comment by axlright** [comment]
I'm down to move them. In most of my client projects, I put everything except page templates in `loop-templates` because I see them as sub-actions of a page template. Whether there is technically an official `while` loop or not. Template parts, for each loops, traditional loops. It's all kind of the same to me. But that's personal / stylistic (which is what all organization is).

I don't personally understand what is meant by `global-templates` but that seems like the best destination if `loop-templates` isn't widely desired. I think making a third directory for `sidebar-templates` is one too many directories considering there are already sidebar functions / template parts in `global-templates`

**Comment by ZacharyElkins** [comment]
I would vote for them being in `global-templates` as `loop-templates` does have a specific definition that they do not fall in.

I wouldn't mind another dir just for the sidebar templates either.

**Comment by davidshq** [comment]
+1 to another folder just for sidebar templates. :)

**Comment by axlright** [comment]
@ZacharyElkins and @Thomas-A-Reinert and @davidshq updated the PR to move sidebar template parts into a `sidebar-templates` directory. Thanks for the feedback!

**Comment by Thomas-A-Reinert** [comment]
👍

**Pull request merged**
