### PR TITLE
Add robots meta tag for no-index if paged/date/category page

### PR DESCRIPTION
**Pull request by gillespieza**
Stop robots indexing the pages where posts are duplicated, if this is a paged page/date/category page, by adding a no-index meta tag for robots.

### CODE REVIEW

**Comment by IanDelMar** [comment]
I'd suggest putting that into [extras.php](https://github.com/understrap/understrap/blob/master/inc/extras.php) like so
```php
if ( ! function_exists( 'understrap_fix_duplicate_content' ) ) {
	/**
	 * Stop robots indexing the pages where posts are duplicated, if this is a paged
	 * page/date/category page.
	 */
	function understrap_fix_duplicate_content() {
		if ( ( is_home() && ( $paged > 2 ) ) || is_date() || is_category() ) {
			echo '<meta name="robots" content="noindex, follow, noarchive" />' . "\n";
		}
	}
}
add_action( 'wp_head', 'understrap_fix_duplicate_content' );
```
and maybe add author, tag, taxonomy archive, search, and 404 pages
```php
if ( ! function_exists( 'understrap_fix_duplicate_content' ) ) {
	/**
	 * Stop robots indexing the pages where posts are duplicated, i.e. archive pages,
	 * search and 404 pages.
	 */
	function understrap_fix_duplicate_content() {
		if ( ( is_home() && ( $paged > 2 ) ) || is_archive() || is_search() || is_404() {
			echo '<meta name="robots" content="noindex, follow, noarchive" />' . "\n";
		}
	}
}
add_action( 'wp_head', 'understrap_fix_duplicate_content' );
```
What do you think?

**Comment by Thomas-A-Reinert** [comment]
Imho that is thing that affects WordPress´ default functionality and therefore should be put into a plugin rather than a theme. Besides it´s a decision that should be made or not made and not something in a theme that changes the default behaviour. As you said Yoast supports that and is one of the most common SEO solutions out there. But there are others that also have this feature.

**Comment by IanDelMar** [comment]
Good point @Thomas-A-Reinert

**Comment by Thomas-A-Reinert** [comment]
Tried to be as neutral as possible :)
In case I could really convince you, it´d be nice if you would close this PR..

**Pull request closed without merging**
