### PR TITLE
Apply pluggable function wrappers

### PR DESCRIPTION
**Pull request by axlright**
Based on issue #550, applying pluggable function wrappers in one file to check with reviewers before continuing on to other files.

@holger1411 @0dp @Thomas-A-Reinert and anyone else take a look at this and let me know if you want it done differently. I don't know if you / others prefer `add_filter()` and `add_action()` to be above or below the functions. I am leaving as-is but I can make them all consistent. 

I also space things out a bit in php to make it more readable but I can cut down on the spaces if people prefer that.

### CODE REVIEW

**Comment by Thomas-A-Reinert** [comment]
Both solutions (calling the function above/below) have their pros´ and cons. See: https://www.quora.com/In-WordPress-is-it-best-practice-to-add_action-before-or-after-your-custom-function

Personally I prefer to just call them ALL in their correct order on top of the file. And I place the complete code of ALL (well documented) functions way below. But that´s just my approach.

Advantage: You see what´s going on one-by-one just on top of the file. if you really need to dig through the code - easy to find.

MakeWordPress recommends using tabs for indentation instead of spaces as almost every editor allows customizing how many spaces they should reflect. But almost any framework handles that differently. Anyway, I´d recommend sticking to WP-Standards here.

**Comment by axlright** [comment]
@Thomas-A-Reinert That's cool about the Quora answer. I've never seen it described as well.

In terms of spacing - I wasn't referring to tabs v. spaces (I don't want to start a Silicon Valley boxing match 👍  I was referring to spacing out the functions a bit:
`if ( ! function_exists ( 'understrap_wpdocs_theme_add_editor_styles' ) )`
versus
`if ( ! function_exists('understrap_wpdocs_theme_add_editor_styles'))`

In terms of tabs v. spaces - I work in tabs and did a full copy paste into the repo with the pull request. I'm seeing all tabs here. Are you seeing spaces in the pull request?

**Comment by Thomas-A-Reinert** [comment]
Oh, sorry about the whitespace confusion :)
Yeap, looks good/better readable with the additional spacing.

**Comment by axlright** [comment]
Thanks @Thomas-A-Reinert - I'm glad we didn't have to break up over tabs vs. spaces :-)

I'll wait for @holger1411 and @0dp and anyone else to weigh in about ordering of functions before or after. I've never seen the actions / hooks all at the top, but it sounds pretty fun. For people who want to copy it out to add to a child theme, that may not be as ideal. 

I'd vote  for adding actions / hooks always above the function for consistency. But I'm kind of a weirdo about consistency.

**Comment by axlright** [comment]
Thanks @Thomas-A-Reinert - I'm glad we didn't have to break up over tabs vs. spaces :-)

I'll wait for @holger1411 and @0dp and anyone else to weigh in about ordering of functions before or after. I've never seen the actions / hooks all at the top, but it sounds pretty fun. For people who want to copy it out to add to a child theme, that may not be as ideal. 

I'd vote  for adding actions / hooks always above the function for consistency. But I'm kind of a weirdo about consistency.

**Comment by Thomas-A-Reinert** [comment]
Well done, @axlright .

Just a personal opinion that should be discussed. Total different approach I tried to explain above but I assume it wasn´t too well understandable. And yes, I know it´s pretty unusual but considered best practise among a good amount of developers. Numbers rising.

Imagine you had the following code instead of yours:

```php
<?php
/**
 * Understrap modify editor
 *
 * @package understrap
 */

/**
 * Registers an editor stylesheet for the theme.
 */

add_action( 'admin_init', 'understrap_wpdocs_theme_add_editor_styles' ); // Add Editor Styles
add_filter( 'mce_buttons_2', 'understrap_tiny_mce_style_formats' ); // Add TinyMCE style formats
add_filter( 'tiny_mce_before_init', 'understrap_tiny_mce_before_init' ); // TinyMCE Before Init


// Add Editor Styles
if ( ! function_exists ( 'understrap_wpdocs_theme_add_editor_styles' ) ) {
  function understrap_wpdocs_theme_add_editor_styles() {
    add_editor_style( 'css/custom-editor-style.min.css' );
  }
}


// Add TinyMCE style formats
if ( ! function_exists ( 'understrap_tiny_mce_style_formats' ) ) {
  function understrap_tiny_mce_style_formats( $styles ) {

      array_unshift( $styles, 'styleselect' );
      return $styles;
  }
}

// Add custom TinyMCE formats
if ( ! function_exists ( 'understrap_tiny_mce_before_init' ) ) {
  function understrap_tiny_mce_before_init( $settings ) {

    $style_formats = array(
        array(
            'title' => 'Lead Paragraph',
            'selector' => 'p',
            'classes' => 'lead',
            'wrapper' => true
            ),
        array(
            'title' => 'Small',
            'inline' => 'small'
        ),
        array(
            'title' => 'Blockquote',
            'block' => 'blockquote',
            'classes' => 'blockquote',
            'wrapper' => true
        ),
        array(
            'title' => 'Blockquote Footer',
            'block' => 'footer',
            'classes' => 'blockquote-footer',
            'wrapper' => true
        ),
        array(
            'title' => 'Cite',
            'inline' => 'cite'
        )
    );
    
      if ( isset( $settings['style_formats'] ) ) {
        $orig_style_formats = json_decode($settings['style_formats'],true);
        $style_formats = array_merge($orig_style_formats,$style_formats);
      }

      $settings['style_formats'] = json_encode( $style_formats );
      return $settings;
  }
}
```

Advantages:
1. Right at the top of the file you straightforward know whats included in it.
2. You don´t have to inspect hundreds/thousands lines of code to get a clue about what´s going on here.
3. By leaving a comment behind the add_filter/add_action hooks that´s absolutely identical to the relevant code block - the code is absolutely easy to find without the need to look through gazillion lines of code again.
4. Hooks/Filters can easily be commented out on top - without searching through the whole **** trying to understand what it actually does. Again. And again. And over and over again.

Did I make myself clear? I got into the whole concept _heavily_ customizing my last WooCommerce site with dozens and dozens of filters and actions that soon became totally confusing.  @GuerrillaCoder @typeplus  - can you feel me? :)

Yes, I know that may be kinda excessive in a file with just three hooks/actions, but image you had a few dozens? And I know there are some files which are quite heaver on hooks/actions in UnderStrap.

Sidenote: The // Add custom TinyMCE formats section is ehm.. well. Most of it is just useless. `<blockquote>` == `class="blockquote"`. Imho there´s just no need to apply a blockquote-class to some non-blockquote content. That´s just pure semantic nonsense.
What is "blockquote-footer" good for?

Never been really aware of the TinyMCE formats section though. Maybe that´s a nice place to integrate some of UnderStraps/BootStraps styles?

**Comment by 0dp** [comment]
What ever path we choose we just need to review the rest of the inc/ files to follow the same style 👍

**Comment by Thomas-A-Reinert** [comment]
Yeap, I´m totally with you. The decision we make HERE will have an impact on EVERY *** thing following up. So we should try to implement the best possible practise - until we change those. Imho changes are a no-go if avoidable though.

Yes, I know, my approach is kinda uncommon. But I hope I could convey it´s advantages. 

Honestly, I don´t need to make my ends meet. I´m just trying to find a solution that makes most transparent for every john-doe to make the functionality fore-seeable asap. The logic that stands behind it, can be handled thereafter. But as I said - that´s just my 2cents.

(I´d hate you if we wouldn´t follow that paradigm within UnderStrap, but *hey* ;) )

**Comment by axlright** [comment]
@Thomas-A-Reinert I conceptually got your proposed idea in the first mention. Seeing it written out makes it even more impactful. I agree with your ideas.

Here's my concerns:

1) What can we do consistently that sets up other developers for success? If a new strategy is better but creates confusion because it's not what developers are expecting, is that a net gain or a net loss?

2) How can we get these functions pluggable without opening up a larger discussion about how functions, filters and actions are listed?

My proposal is this - make a first pass making the functions pluggable and consistently listing filters above functions but using the more traditional approach of filter A, function A, filter B function B rather than filter A, filter B, function A, function B.

We can then make further changes later. It's no biggie to me - I have a little snippet written in Sublime Text and I just copy the name of the function, activate the snippet and the rest is mostly automated.

I'm going to work on a file at a time and add commits to this Pull Request. I'm happy to make adjustments. It's all copy paste. Not like digging ditches or laying bricks or "real work."

**Comment by axlright** [comment]
@Thomas-A-Reinert @0dp @holger1411 that should be it for the inc/ directory. Nothing other than pluggable wrappers and action / function order was changed * except in inc/pagination.php I got a php error in my test install for pagination - the `{ echo active; }` without quotes was making it look for a constant called active.

There are a couple files that have all pluggable functions but the actions below the functions. I didn't change those just to avoid changes. I can.

It'd probably be a good idea for someone to git these changes a test before merging. I'll export the theme with these changes and test on a few websites to see if I find any changes.

Thanks!

**Comment by 0dp** [comment]
@axlright hahaha nice you cought it. My setup didn't catch that one, but clearly JavaScript have gotten to me

**Comment by Thomas-A-Reinert** [comment]
@axlright .. I totally understand your concerns. Anyway, we should try to improve or stick to the better choice. "_Evolution_",  you know? ;) Standards are good, but what to do if better standards evolve? They´ll eat the lower ones. For sure. So let´s go take a step ahead if we want to make a change and become standard in the WP-World!

As far as WordPress standards are concerned - and that would be the only ones we´d HAVE to yield to! - there ARE none. You can see all of those I mentioned above in the wild. So we´re totally free implementing our own, (improved!?) standards. It SHOULD be so ******* understandable that it shouldn´t need no explanation. But *HEY* I know how the world works :) - let´s make it easy for every du_b_ss and leave a comment atop and everything should be okay, don´t you think?

Besides: Everything seems cool so far! Thanks for your engagement!

**Comment by axlright** [comment]
Thanks for the comments @0dp and @Thomas-A-Reinert 

I did end up replacing some of the previous wrappers that used the shorthand if( xx ) : endif rather than if ( xx ) {} just to be consistent. I did not go into files that had the actions below the functions if no other edits needed to be made (if there were already pluggable functions). And lastly, some of the closing endif / } had // comments to note the close of the pluggable functions. I didn't take out those comments but I didn't add my own.

I have a test install running with the code and it didn't turn up any issues beyond the class name for the pagination. My test install is pretty virgin, though - not a lot of content. I can apply that inc/ directory into a couple local production websites to test further. I'll see if I can do that this weekend.

**Comment by Thomas-A-Reinert** [comment]
Thanks for replacing if/endif clauses. The never made any sense to me in case of "transparency". Also thanks for outlining that this is not consistent through the whole thingie yet. We should try to improve on that.

Anything else: There´s still nuff space for improvement. But thats none of the problems that gots to be solved with the initial request. "Apply pluggable function wrappers". The rest can be done/discussed later on.

Thanks for your efforts, @axlright !

**Pull request merged**
