### PR TITLE
Update author.php

### PR DESCRIPTION
**Pull request by IanDelMar**
## Description

This PR
- updates message ids to be rtl compatibel.
- replaces the title 'About: ' + author nickname by WPs default title for author archives and adds the class `.page-title` (consistency with other archive pages).
- replaces the author's nickname with their display name.
- introduces a template partial for the loop producing a layout similar to that of the search results page.
- replaces the message id 'Profile' with 'About %s'.
- drop the message id 'Permanent Link:'.

Summary: This PR fixes and reduces translation strings and increases the archive's consistency with the rest of the theme.

## Motivation and Context

- The author template is "broken" since #856 (thanks to myself). Note the missing spaces between words. 
image
- `understrap_posted_on()` echos the posted by information by default which is redundant on the author archives.
- The author archive page is the only place where posts are displayed as an unordered list. Displaying it either like the search results or the any other archive increases consistency.

The author archive page now looks like:

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

Unfortunately this comes with a price...

## Checklist:

- [x] I have checked that there aren't other open Pull Requests for the same update/change.
- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] \(Optional) My change requires a change to the documentation.
- [ ] \(Optional) I have updated the documentation accordingly.
- [x] \(Optional) My change requires a change to the translations.
- [x] \(Optional) I have updated the translations accordingly.
- [x] `composer cs:check` has passed locally.
- [x] `composer lint:php` has passed locally.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by IanDelMar** [comment]
@Thomas-A-Reinert what would you think about adding a default alt text to the avatar saying "profile picture". AFAIK the visually impaired community does not like if something is hidden. So they would at least know there is profile picture even if we cannot provide a description of that profile picture.

**Comment by bacoords** [comment]
On sites where we spend a lot of time optimizing SEO/accessibility, we typically add the user's display name as alt text for the image. I feel like it should be standard practice in WordPress

**Comment by IanDelMar** [comment]
@bacoords The profile picture does not necessarily show the author. Look at my Github profile picture. While Github uses "@IanDelMar" as alt text, I'm pretty sure that isn't me.

**Comment by 0dp** [comment]
What about the best of both worlds and have `profile picture - $authorName`

**Comment by IanDelMar** [comment]
Sounds good to me. I cannot push to merged PRs, right?

**Comment by 0dp** [comment]
> Sounds good to me. I cannot push to merged PRs, right?

I think you got to make a new one

**Comment by danemorgan** [comment]
Sorry about that. I'm trying to get a bunch of your PRs into development so I can test them all at once. I pulled the trigger here, and then thought, maybe I should have waited a bit on that one.

**Comment by IanDelMar** [comment]
No worries. I'll make a new one. No big deal.

**Pull request merged**
