### PR TITLE
Delete .DS_Store

### PR DESCRIPTION
**Pull request by IanDelMar**

### CODE REVIEW

**Comment by 0dp** [comment]
Are they added to . gitignore?

**Comment by IanDelMar** [comment]
.DS-Store has been added to .gitignore in #650 by @0dp ;-) but these .DS-Store files have not been removed.

**Comment by 0dp** [comment]
Ohh yeah hahaha

**Comment by IanDelMar** [comment]
@UnderstrapFramework please merge!

**Comment by UnderstrapFramework** [comment]
Done, thanks for pinging me

**Pull request merged**
