### PR TITLE
Updated WooCommerce template files to 3.3.4 release

### PR DESCRIPTION
**Pull request by ZacharyElkins**
I've updated WooCommerce template files to the latest release: 3.3.0

I've tested and all appears to be working.

# Notes

1. Now uses esc_html instead of _e
2. Removed capitalization of several sentences. IE: "Apply coupons"
3. Several changes of `<input>` to `<button>`

**Files I suggest for removal from Understrap, as they are identical:**

- single-product/add-to-cart/simple.php
- single-product/product-thumbnails.php
- single-product/review-rating.php
- single-product/short-description.php

### product-searchform.php
- Added `screen-reader-text` label, noticed this was originally removed. Please comment.
- Line 27 contains `field` class, please comment.

### checkout/form-pay.php and checkout/payment.php
- Should we consider replacing WooCommerce notice classes with Bootstrap alert classes? Perhaps this is a bit much.

### loop/add-to-cart.php
- Left custom changes
- Re-removed removed class esc_attr line

### myaccount/form-login.php
- Added form-control class to lines 45, 49, 85, 92, 99

### myaccount/orders.php
- There was no change to button class on line 89, however, there was to line 93. Why? This is for pagination, which the next button has been given classes `btn btn-outline-primary`.
**Important item, please review**

### CODE REVIEW

**Comment by Thomas-A-Reinert** [comment]
Hi @ZacharyElkins  let me first really, really thank you for your commit.

*Note:* I´ll not be the one to merge it. But I´ll keep the woo-team posted that has currently been working on it, too. So the following are just my personal opinions, ´kay?

Some small suggestions before I get to the nitty-gritty and answer your questions.

1. Make small changes. Each for one topic. Submit a pull request for each. That makes it much easier to follow, merge or decline a pull request.
2. It seems that every file has a merge conflict, see above.
3. It seems like a good idea, I know. And I do it for certain projects too that do NOT get submitted to the WordPress Codex/Theme Repo. But I remember that there is a problem changing all "woocommerce" text-domain strings to "understrap". Sorry, but I cannot recall it. Try to find it through the issue-tracker please. But i´ll ping @holger1411 - I recall that he mentioned something about that if I´m not all wrong.


> ***product-searchform.php***
Added screen-reader-text label, noticed this was originally removed. Please comment.

Can´t tell why it was removed. But in this case - and in every other concerning the "*screen-reader-text*" class it should be replaced with the Bootstrap-class "*sr-only*". It just makes no sense to have two classes that are meant to do the same thing. And i´m pretty sure that the BS-classes are deeper investigated, better supported in the future etc. So i´d just get rid of the Underscore classes whereever posssible. Just my 2cent.

> ***checkout/form-pay.php and checkout/payment.php***
Should we consider replacing WooCommerce notice classes with Bootstrap alert classes? Perhaps this is a bit much.

Personal opinion: Yes, we should. Again: it makes no sense to maintain duplicate classes that are meant to do the same. As Bootstrap 4 is still evolving and Underscores is just the base built upon, I´d personally go for the Bootstrap way.

> myaccount/orders.php
There was no change to button class on line 89, however, there was to line 93. Why? This is for pagination, which the next button has been given classes btn btn-outline-primary.
Important item, please review

Makes no sense. I guess someone just did a search and replace and forgot something. Good to go for an add/replacement on the other button the way I see it.

**Comment by typeplus** [comment]
My commit for the 3.3.0 vanished so I dont know what is going on. Happy to check this one over compared to my local copy which I have confirmed as working in the wild. Makes sense rather than to push another commit to confuse things further.

**Comment by ZacharyElkins** [comment]
@Thomas-A-Reinert 
1. Do you mean to make pull requests for each file? I can do that, and/or make staggered commits for each significant line. 
2. I’ll have to check and review. I didn’t look at the pull request after, but it is comparing it to versions of the files that aren’t the latest in the repo, a bit confused here.
3. This goes with the above. It’s comparing it to files with ‘woocommerce’ text-domains string instead of ‘understrap’, which the files I used for editing had ‘understrap’, among other differences. I merely changed any WooCommerce changes (compared to the version the Understrap files were created from) and retained any edits that were made for Understrap. I think I remember them being changed back and forth quite a while ago, so hopefully someone can shed some light here. 

One thing to note is that the WooCommerce notices are quite different from the Bootstrap alert boxes. Something to consider. But, I would agree that it should be changed to Bootstrap, which would make theme styling easier and more uniform.

@typeplus Yes, please review. I don’t by any means say these have been trialed. I made all the changes in hope that others could use it as a base and make sure it is vetted.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Thomas-A-Reinert** [comment]
Hi @ZacharyElkins,
again, I´m just issueing my own, personal opinion which may or may not be in accordance with UnderStraps/ and or @holger1411´s personal choice.

1. Nope I don´t really mean for each file. I mean for one TOPIC, like: "Changing textdomain from woocommerce to understrap". This may include multiple files, but is just according to ONE single Topic. Do you know what I mean? So if that is declined it can be declined as a whole without inflicting other pull-requests,
2. Would love to help - but cant. Sorry. 
3. Yeap. I´m totally with you. Guess only @holger1411 can do that, as he is the one who has been contributing it to WP and as far as I remember there have been some problems changing the text-domain.

As for your last comment: We´re not perfect. We just try. 
But I really guess (hope?) that none of us found the philosopher's stone.  Anyway - we´re working on it ;)
Though i know and really hope, that there are other developers who know a LOT more about their "little, specific section", we really want to welcome and learn from them!

Curently we´re just trying to learn from each other and to implement the best possible practices. So your commit is really, really welcome and will be considered by the  [Woocommerce Team](https://github.com/orgs/understrap/teams/woocommerce-team)

**Comment by typeplus** [comment]
@ZacharyElkins You did a great job and thanks for going to all that effort 😉  As @Thomas-A-Reinert was suggesting its a bit easier to have separate issues as separate pull requests.

**Re the Translation / text-domain** - As far as I know the text-domain was changed back to woocommerce from understrap as there were issues. Woocommerce translations [https://docs.woocommerce.com/document/woocommerce-localization/](url) as it appears we dont actually have any in place. I cant see anything in the setup.php or woocommerce.php for loading locales for translation when it comes to woocommerce. @holger1411 can you confirm on this issue of woocommerce translations and if there is need for a custom text-domain?

**Comment by ZacharyElkins** [comment]
It seems that when I created that fork the files were from Oct., 2017, so it's diffing with those.
Not sure how that happened. I'll have to check.

The files I used for conversion were the latest, downloaded locally.

Here it shows using "understrap" for text-domain if I'm not mistaken.
[https://github.com/understrap/understrap/blob/master/woocommerce/cart/cart-empty.php](https://github.com/understrap/understrap/blob/master/woocommerce/cart/cart-empty.php)

Sorry, I haven't used git extensively beyond tracking changes for projects.

**Comment by ZacharyElkins** [comment]
Anyone know what the best way to resolve this is?

The fork I made is from 2017, which I thought had updated when I recreated it. (Forgot I already had a fork.)

I need to update my fork with the original understrap, then resubmit this pull request so it shows the diff comparing to the current version files, as it should. 

I can delete remove this one and resubmit smaller requests? Or is there a way to update this one? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ZacharyElkins** [comment]
Ok. 

1. This PR has been rebased on to the latest Understrap commit.
2. I've also separated it into smaller commits to better explain which each change is.

For clarification: I've only made the changes WooCommerce has made to their templates, which may be very important soon when/if they take away support for the old templates. Beyond this, I added form-control to a few forms.

Please again note the files I recommend for deletion, as they are identical to Woo source files:

- single-product/add-to-cart/simple.php
- single-product/product-thumbnails.php
- single-product/review-rating.php
- single-product/short-description.php


I've made a few notes for changes that are Understrap specific but will hold off on committing them until this PR is resolved. There may be gains in investigating reducing the number of templates and using other methods to get the Bootstrap classes on buttons and inputs, which is most of what these templates are for. Then there wouldn't be any need to upkeep templates, and Understrap would be leaner.

**Comment by ZacharyElkins** [comment]
I've rechecked the files to WooCommerce 3.3.4 release.
Also made a few changes to Bootstrap implementation.

Keep in mind that the version of the files does not need to be the latest WooCommerce release (3.3.4), but instead it uses the latest version of the template file, which can be 2.4.0, etc.

**Comment by ZacharyElkins** [comment]
I had to revert the changes to add-to-cart, as it automatically adds the WooCommerce 'button' class.

I've added a new commit that removes the template and uses a function instead, let me know thoughts on this. I'm concerned it may be over-complicating for people who would like to change the button to solid, etc. However, if we switched all the templates to a function it could be easier.

Let me know if I should revert this commit.

**Comment by stef-k** [comment]
Hi @ZacharyElkins and all, first of all I resurfaced to congratulate all contributors for their efforts. 

You are all  doing a great work and especially @holger1411.

I am sorry for my absence  but due to other engagements and projects not related to WordPress, I do not have the time to contribute.  

Since I was the one who incorporated the enhanced Woo support for UnderStrap, I would like to say that supporting a plugin such as Woo needs big effort. Given the few hands contributing to UnderStrap all I can say you are all doing good job.

IMO the integration efforts should be minimal in order to be able to cope with the continuous incremental Woo versions. IMO as UnderStrap targets developers,  you could avoid getting in fine grained integration. Provide the basic support from which developers can pick up and start working in their projects.

As for new PRs, as @Thomas-A-Reinert stated, it would be good idea to try to submit a PR per topic - idea - fix or at least per file. This way, changes are more manageable and potential errors are easier to spot.

**Comment by holger1411** [comment]
@ZacharyElkins It seems you downgraded the version info in some file. From 3.3.2 to 3.10 or 3.3.0 or even 2.4.0. Any resons for this?

From my point of view it looks cool. But we have to test it live before we release the next UnderStrap version. There are a lot of changes and I´am not really into WC...

**Comment by ZacharyElkins** [comment]
@holger1411  The reason for downgrade is that the template files are given versions different from the current WooCommerce version. While some may be 2.4.0, that would be the latest version of that file according to WooCommerce. This allows us to check what version the file is based on so when they update a template we can verify it has been updated and from what/when so we can make proper changes easier. If you check the WooCommerce repo, you’ll find the same version I’ve changed it to on the corresponding file. 

I agree this needs to be tested. I have it testing on one live site, at the moment.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by holger1411** [comment]
@ZacharyElkins: Okay got it!
Merging this. We should test it carefully before the 0.8.2 release...

**Comment by ZacharyElkins** [comment]
@holger1411  I meant the following as a test or example:
https://github.com/understrap/understrap/pull/599/commits/61dbdfcde33f6f8fa732680cae13b38eec773172

With that function, we no longer need the loop/add-to-cart.php

I was thinking of removing the function and leaving the modified add-to-cart.php instead. This is me re-replacing the new Woo code with the previous Understrap code:
https://github.com/understrap/understrap/pull/599/commits/ae5790b8440d93a033f08dfc11c46fc2c4eeb073

IF we are to keep the function, the modified add-to-cart.php needs to be removed. I don't think they will conflict, but the function won't work without the original add-to-cart.php code from WooCommerce plugin templates, so there are 2 pieces of code providing the same output.

The reason for removing the function is that it will likely be easier for devs to understand and edit the Woo templates, the function was just an example that some of the templates could be removed and converted to functions.

**Pull request merged**
