### PR TITLE
Fix 2 outdated WooCommerce templates

### LINKED ISSUE #1167: form-login and quantity-input templates out of date
This is a bug report.

  - **WordPress Version:** 5.4.1
  - **OS Version:** MacOS 10.11.1
  - **Browser:** Firefox 76.0.1
  - **WooCommerce Version:** 4.1.0

---

My WordPress dashboard says that my UnderStrap theme contains outdated WooCommerce template files. My WooCommerce status page says these template overrides are out-of-date:

understrap/woocommerce/global/quantity-input.php version 3.6.1 is out of date. The core version is 4.0.0, 
understrap/woocommerce/myaccount/form-login.php version 3.6.1 is out of date. The core version is 4.1.0,

### PR DESCRIPTION
**Pull request by IanDelMar**
## Description
- Removes `woocommerce/global/quantity-input.php`  
- Updates `woocommerce/myaccount/form-login.php` to WooCommerce 4.3.

Removes `woocommerce/global/quantity-input.php`: The only difference to the original file provided by WooCommerce was the replacement of `screen-reader-text` with `sr-only`. `screen-reader-text` is provided by both theme.css and woocommerce.css. There is no need to replace it. The Bootstrap class `.form-control` was missing - it is now added via the `woocommerce_quantity_input_classes` hook. The following translations are then obsolete: ( '%s quantity', 'understrap' ), ( 'Qty', 'Product quantity input tooltip', 'understrap' ). Translation files not updated yet.

Updates `woocommerce/myaccount/form-login.php`: Adds missing `.form-control` class to form fields. Fixes the first column being set to col-md-6 even if there is no second column. Keeps `.woocommerce-form-login__submit` and `.woocommerce-form-.register__submit`. The first is used in WooCommerce's native rtl CSS.

## Motivation and Context
Fixes #1167.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have checked that there aren't other open Pull Requests for the same update/change.
- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] \(Optional) My change requires a change to the documentation.
- [ ] \(Optional) I have updated the documentation accordingly.
- [x] \(Optional) My change requires a change to the translations.
- [ ] \(Optional) I have updated the translations accordingly.
- [x] `composer cs:check` has passed locally.
- [x] `composer lint:php` has passed locally.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by IanDelMar** [comment]
@noelspringer you might want to take a look at this.

**Comment by noelspringer** [comment]
Thanks for the heads up @IanDelMar. Cheers

**Comment by IanDelMar** [comment]
@UnderstrapFramework please merge

**Comment by UnderstrapFramework** [comment]
Thanks @IanDelMar

**Pull request merged**
