### PR TITLE
[WIP] Revert "Add `understrap_edit_post_link()` to display the edit post link"

### PR DESCRIPTION
**Pull request by danemorgan**
Reverts understrap/understrap#1325

### CODE REVIEW

**Comment by danemorgan** [comment]
@IanDelMar I did a revert. Does this help?

**Comment by IanDelMar** [comment]
I don't think so. Commit 8758ad4 which includes the translation updates does not show up anywhere. Just close this PR and make a new one with the translation files.

**Comment by IanDelMar** [comment]
Nope, doesn't work. I'm not going to resolve all the conflicts a third time.

**Comment by IanDelMar** [comment]
@danemorgan you can close this PR. I made a new one (#1335) which was already merged by @bacoords.

**Pull request closed without merging**
