### PR TITLE
Bump Bootstrap 4 and 5

### PR DESCRIPTION
**Pull request by IanDelMar**
## Description
This PR bumps
* Bootstrap 4 from 4.6.1 to 4.6.2 - [release notes](https://github.com/twbs/bootstrap/releases/tag/v4.6.2)
* Bootstrap 5 from 5.1.3 to 5.2.0 - [release notes](https://github.com/twbs/bootstrap/releases/tag/v5.2.0)

## Motivation and Context
Keeping Bootstrap up to date.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I pulled my branch from `develop`.
- [x] I am submitting my pull request to `develop`.
- [x] I have resolved any conflicts merging this pull request would create.
- [x] I have checked that there aren't other open Pull Requests for the same update/change.
- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] \(Optional) My change requires a change to the documentation.
- [ ] \(Optional) I have updated the documentation accordingly.
- [ ] \(Optional) My change requires a change to the translations.
- [ ] \(Optional) I have updated the translations accordingly.
- [x] `composer cs:check` has passed locally.
- [x] `composer lint:php` has passed locally.
- [x] I have read the **[CONTRIBUTING](https://github.com/understrap/understrap/blob/main/.github/CONTRIBUTING.md)** document.

### CODE REVIEW

**Comment by bacoords** [comment]
One issue with the homepage widget slider: We've been using `data-interval=false` to disable the autoplay on the carousel (as an accessibility default. see: https://make.wordpress.org/themes/handbook/review/accessibility/required/#media). 

It looks like starting in BS 5.2.0, this causes it to think we want the interval to be 0 seconds and just animate super fast.

**Comment by IanDelMar** [comment]
You're right. `data-interval=false` does no longer block autoplay. An alternative could be `data-bs-ride=true`.

**Comment by bacoords** [comment]
Nice- I can verify that `<div id="carouselExampleControls" class="carousel slide" data-ride="false" data-bs-ride="false">` works just fine if you want to fix the PR.

**Comment by IanDelMar** [comment]
`data-ride="false"` is not sufficient to stop autoplay in Bootstrap  4. While it does block auto start, it autoplays after user interactions. We have to keep `data-interval="false"`. But we can remove `data-ride` as its value does not have any effect after setting  `data-interval="false"`.

From the options table of the [Bootstrap 4.6 docs](https://getbootstrap.com/docs/4.6/components/carousel/#via-data-attributes):
| Name     | Type              | Default | Description                                                                                                                                                                                                                                                                                                                                                                                                                              |
|----------|-------------------|---------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| interval | number            | 5000    | The amount of time to delay between automatically cycling an item. If false, carousel will not automatically cycle.                                                                                                                                                                                                                                                                                                                      |
| ride     | string            | false   | Autoplays the carousel after the user manually cycles the first item. If set to 'carousel', autoplays the carousel on load.

**Comment by bacoords** [comment]
@IanDelMar Do we know why the PHPStan analysis is failing? (I know this is not really related to the changes here). 

It looks like the `esc_attr( get_the_date( 'c' ) )` on https://github.com/understrap/understrap/blob/main/inc/template-tags.php#L24 is an example of it failing due to `get_the_date()` potentially returning `false`.

**Review by bacoords — APPROVED** [review]

**Pull request merged**
