### PR TITLE
Replace understrap_kses_title() with wp_kses_post()

### PR DESCRIPTION
**Pull request by IanDelMar**
## Description
This PR deprecates the `understrap_kses_title()` filter and replaces it with `wp_kses_post()`.

## Motivation and Context
`understrap_kses_title()` causes issues by aggressively stripping HTML from titles. To escape titles with `wp_kses_post()` is less strict but still strips scripts from titles.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I pulled my branch from `develop`.
- [x] I am submitting my pull request to `develop`.
- [x] I have resolved any conflicts merging this pull request would create.
- [x] I have checked that there aren't other open Pull Requests for the same update/change.
- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] \(Optional) My change requires a change to the documentation.
- [ ] \(Optional) I have updated the documentation accordingly.
- [ ] \(Optional) My change requires a change to the translations.
- [ ] \(Optional) I have updated the translations accordingly.
- [x] `composer cs:check` has passed locally.
- [x] `composer lint:php` has passed locally.
- [x] I have read the **[CONTRIBUTING](https://github.com/understrap/understrap/blob/main/.github/CONTRIBUTING.md)** document.

## Related Issues or Roadmap requests
#1305
#1468
#1648
#1849

### CODE REVIEW

**Comment by IanDelMar** [comment]
@bacoords ready for review

**Comment by bacoords** [comment]
@IanDelMar This is a much better approach. When you have time can you fix the conflicts from me pulling in the other PRs?

**Comment by IanDelMar** [comment]
@bacoords done

**Comment by bacoords** [comment]
I was hoping this would fix the issue with Polylang using images in the nav menu items (https://github.com/understrap/understrap/issues/1305) like it does with WPML (https://github.com/understrap/understrap/issues/1468) but the images still don't work. This is because they're using data URIs for the flag icons.

My assumption is that we'd need to re-open that old issue if we went this route (I still like this approach) and then either 
add the 'data' protocol to [`kses_allowed_protocols`](https://developer.wordpress.org/reference/hooks/kses_allowed_protocols/) or else add some documentation explaining how to do it for Polylang users.

Or we need to take step back and decide why we're even sanitizing titles to begin with and if this is a common practice.

**Comment by IanDelMar** [comment]
> Or we need to take step back and decide why we're even sanitizing titles to begin with and if this is a common practice.
>

I don't think that it is common practice. The reason I added this was that titles are not sanitized and, e.g., a malicious plugin can add a script. Probably this was too ambitious. We do not sanitize `the_content()` either. In terms of the original purpose it may be sufficient to just strip script tags and onclick attributes? At the end of the day, you can't force the title or the content to be "scriptless" via a filter unless it's priority is infinitely large. You can only make sure that a script already stored in the database will not be executed.

**Comment by bacoords** [comment]
@IanDelMar Closing this in favor of https://github.com/understrap/understrap/pull/1927

**Pull request closed without merging**
