### PR TITLE
Update translations (pot, po & mo)

### PR DESCRIPTION
**Pull request by IanDelMar**
## Description
This PR updates a couple of translations mostly with the translation provided in core translations.

## Motivation and Context
Reduce number of untranslated strings.

Current State:
image

Post PR Status:
image

## List of translations sources
| MSGID                                                                | SOURCE                                  |
| --------------------------------------------------------------------- | --------------------------------------- |
| It looks like nothing was found at this location. Maybe try a search? | Theme: Twenty Twentyone                 |
| Profile picture of %s                                                 | Buddy Press                             |
| Posts by %s                                                           | WordPress 6.0.1                         |
| One thought on &ldquo;%s&rdquo;                                       | Theme: Twenty Sixteen or smaller        |
| %1$s thought on &ldquo;%2$s&rdquo;                                    | Theme: Twenty Sixteen or smaller        |
| %1$s thoughts on &ldquo;%2$s&rdquo;                                   | Theme: Twenty Sixteen or smaller        |
| Main Navigation                                                       | Apps: WordPress for iOS                 |
| Toggle navigation                                                     | WordPress 6.0.x                         |
| Skip to content                                                       | WordPress 6.0.1                         |
| Add a menu                                                            | WordPress 4.8.x                         |
| Previous                                                              | WordPress 6.0.1                         |
| Next                                                                  | WordPress 6.0.1 admin                   |
| Profile                                                               | WordPress 6.0.1                         |
| Small                                                                 | WordPress 6.0.1                         |
| Blockquote                                                            | WordPress 6.0.1                         |
| Version: %s                                                           | WordPress 6.0.1 admin                   |
| &laquo;                                                               | WordPress 6.0.1                         |
| &raquo;                                                               | WordPress 6.0.1                         |
| Primary Menu                                                          | Meta: Learn WordPress                   |
| ,                                                                     | WordPress 6.0.1                         |
| Posted in %s                                                          | Meta: WordCamp                          |
| Tagged %s                                                             | Theme: Twenty Twentyone; Meta: WordCamp |
| comments navigation                                                   | WordPress 6.0.1                         |
| &larr; Older Comments                                                 | WordPress 6.0.1                         |
| Newer Comments &rarr;                                                 | WordPress 6.0.1                         |
| Post navigation                                                       | WordPress 6.0.1                         |

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I pulled my branch from `develop`.
- [x] I am submitting my pull request to `develop`.
- [x] I have resolved any conflicts merging this pull request would create.
- [x] I have checked that there aren't other open Pull Requests for the same update/change.
- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] \(Optional) My change requires a change to the translations.
- [x] \(Optional) I have updated the translations accordingly.
- [x] `composer cs:check` has passed locally.
- [x] `composer lint:php` has passed locally.
- [x] I have read the **[CONTRIBUTING](https://github.com/understrap/understrap/blob/main/.github/CONTRIBUTING.md)** document.

## Further comments
For discussion: I think child themes should use their own text domain. Then we can drop the "deprecated translations" and clean up the pot/po/mo files.

### CODE REVIEW

**Comment by IanDelMar** [comment]
@bacoords what are your thoughts on "deprecated translations"?

**Comment by bacoords** [comment]
The default child theme uses a separate text-domain, so we should be fine. I'm ok removing the deprecated translations since they'll still be available in the GitHub history, correct?

**Comment by IanDelMar** [comment]
> The default child theme uses a separate text-domain, so we should be fine. I'm ok removing the deprecated translations since they'll still be available in the GitHub history, correct?

Yes, they will be available.

**Comment by bacoords** [comment]
Then that's fine with me.

**Review by bacoords — APPROVED** [review]

**Pull request merged**
