### PR TITLE
Remove .skip-link

### PR DESCRIPTION
**Pull request by IanDelMar**
The functionality of .skip-link is provided by .sr-only, which itself is partly overwritten by .skip-link.

### CODE REVIEW

**Comment by pattonwebz** [comment]
This makes sense to me, should the `.skip-link` class also be removed inside the `header.php`?

**Comment by IanDelMar** [comment]
@pattonwebz Thanks to your comment I had a look at this PR again and noticed the old story of removeing/re-structuring/ etc. may break child themes which do not have the `.sr-only` in their `header.php` yet.  So I elaborated on the PR.  I introduced a `deprecated.scss` and put the `.skip-link` there. I think it's now safe to remove `.skip-link` class from the header unless a child theme uses it for JS stuff. However, I'd suggest to have an `#skip-link` id for those who want to target this element by JS.

**Comment by IanDelMar** [comment]
`.skip-link` is the default class used by `skip-link-focus.js` (see https://github.com/cedaro/skip-link-focus) - so closing this.

**Comment by IanDelMar** [comment]
Was looking at the wrong repo. UnderStrap is using the undescores-for-npm packages for this. `skip-link-focus-fix.js` does not rely on any class. Reopen...

**Comment by 0dp** [comment]
When I was doing the works on the gulp4 or #883 I noticed that it's really not a lot of stuff from underscores that is being used. 
Skip-link and media seems to be the only two things being used from the npm package.
Correct me if I am wrong, but do we really need underscores as a dependency for the theme?

**Pull request closed without merging**
