### PR TITLE
Update _variables.scss

### PR DESCRIPTION
**Pull request by gettonet**
Allow overriding of colors by adding map-merge to $colors and $theme-colors

### CODE REVIEW

**Comment by IanDelMar** [comment]
This is a Bootstrap source file. All changes made to this file will be lost on the next Bootstrap update. If you want to propose changes to Bootstrap files, I'd suggest to open a PR in the Bootstrap repository: https://github.com/twbs/bootstrap

However, you can use custom colors by adding this to your theme.scss:
```diff
@import "theme/theme_variables";  // <-------- Add your variables into this file. Also add variables to overwrite Bootstrap or Understrap variables here
+
+ $my-colors: (
+   "mycolor1": white,
+   "mycolor2": black
+ );
+
+ @import "assets/bootstrap5/functions"; // Required
+ @import "assets/bootstrap5/variables";
+
+ $theme-colors: map-merge($theme-colors, $my-colors);
+
@import "assets/bootstrap5/bootstrap";      // <-------- Loads Bootstrap4
@import "theme/understrap";  // <-------- Loads the Understrap defaults. Just a few classes to incorporate BS in WP
@import "theme/colors";           // <-------- This creates the necessary bootstrap color classes.
@import "theme/blocks";           // <-------- This adds Bootstrap styles to blocks.
@import "theme/contact-form7";    // <-------- Contact Form 7 - Bootstrap 4 support
@import "theme/woocommerce"; // <-------- Loads WooCommerce style fixes. Comment out if you aren't using WooCommerce

// Optional files - If you dont use the corresponding scripts/fonts comment em out
@import "assets/fontawesome/font-awesome";    // <-------- Font Awesome Icon font

// Any additional imported files //
@import "theme/theme";            // <-------- That's where you can add your own design. Thats your part!
```

**Comment by gettonet** [comment]
Thanks @IanDelMar , I missed the point that it's BS source file.

**Comment by gettonet** [comment]
@IanDelMar 

FYI this workaround is not creating necessary text- and bg- classes
As described here: [https://github.com/twbs/bootstrap/issues/35297](https://github.com/twbs/bootstrap/issues/35297)

**Comment by bacoords** [comment]
This is a bummer, but it makes sense to wait for BS 5.2 at this point rather than write a custom fix here

**Pull request closed without merging**
