### PR TITLE
Fix for #976

### PR DESCRIPTION
**Pull request by IanDelMar**
Declare `wc_reviews_enabled()` and `wc_reviews_enabled()` on frontend only.

### CODE REVIEW

**Comment by IanDelMar** [comment]
@holger1411 I think this fix is important

**Comment by Beaniie** [comment]
> Declare `wc_reviews_enabled()` and `wc_reviews_enabled()` on frontend only.

Could you elaborate? Where would these need to be declared?

Regards, 
-B.

**Comment by IanDelMar** [comment]
In `inc/woocommerce.php` replace
```php
if ( ! function_exists( 'wc_review_ratings_enabled' ) ) {
```
by 
```php
if ( ! is_admin() && ! function_exists( 'wc_review_ratings_enabled' ) ) {
```

**Comment by pattonwebz** [comment]
This looks good to me. Activated the theme (with this PR code change), activated Woocommerce. I get no fatal error :)

**Pull request merged**
