### PR TITLE
Added gulp deploy to upload dist-prod files to server

### PR DESCRIPTION
**Pull request by kingsolo50**
## Description

Added gulp ftp and gulp util to enable file upload to server.

## Motivation and Context

This will make the project more fully loaded able to cater for a project from start to finish.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have checked that there aren't other open Pull Requests for the same update/change.
- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] \(Optional) My change requires a change to the documentation.
- [ ] \(Optional) I have updated the documentation accordingly.
- [ ] \(Optional) My change requires a change to the translations.
- [ ] \(Optional) I have updated the translations accordingly.
- [ ] `composer cs:check` has passed locally.
- [ ] `composer lint:php` has passed locally.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by danemorgan** [comment]
Hi @kingsolo50,

Thanks, this looks like it could be useful to me, but I think we have some work to do still.

What happens if someone fails to fill in the config file?

I wonder what the adoption rate on this will be. We want to be sure that anything we add to the code is going to be used by a good percentage of users. If only a few will be using it, it seems more appropriate to provide directions for them to add it.

I'm not sure if there is a way to conditionally include this, though presumably, we could comment it out, and then people who want to turn it on can uncomment it?

I think before we add anything that needs configuration as this does, we at least need to provide instructions in the readme to go along with it.

**Comment by bacoords** [comment]
I'm going to cast my imaginary vote against merging this unless we see additional comments from other contributors. I find this to be a pretty specific use case and not very broadly applicable. I could definitely be wrong, but this seems like personal fork territory to me.

**Comment by 0dp** [comment]
I'm not a big fan of this.
Someone could naively distribute and expose ftp credentials by mistake.

Also I've never had the need to deploy my projects like this.
Just my two cents.

**Comment by danemorgan** [comment]
Good enough for me, there are webhooks and other tools for this that seem safer.

**Pull request closed without merging**
