### PR TITLE
Add id to nav

### PR DESCRIPTION
**Pull request by IanDelMar**

### CODE REVIEW

**Comment by 0dp** [comment]
@UnderstrapFramework Who are you?

**Comment by UnderstrapFramework** [comment]
Hey, I have taken over from Holger and now manage UnderStrap

**Comment by Thomas-A-Reinert** [comment]
How about introducing yourself?

**Comment by UnderstrapFramework** [comment]
Hey im Alex and iv taken over from Holger, im trying to keep UnderStrap following the same course as it was.... simple and lightweight

Any help you guys can give me concerning the pull requests etc. with this project would be massively helpful

**Comment by Thomas-A-Reinert** [comment]
So who are you? What happened to Holger? Why did you take over the project? What do you have to do with understrap so far? Why was none of us - who support this project for Years - asked to continue the project?

**Comment by UnderstrapFramework** [comment]
I'm not sure why he did not ask you guys to take over the project

I'm a freelance WordPress developer in the UK and felt that I could take UnderStrap further so took it over from him

**Comment by 0dp** [comment]
This is very strange!

We've been trying to get hold of Holger for months now. 
Then you pop up out of no where, and say you've taken over the project?

I've never seen you participate in the conversations here, and I don't believe you are part of any of the designated teams?

**Comment by UnderstrapFramework** [comment]
I'v been overseeing it for just over 3 months now, should probably have introduced myself earlier!

**Comment by 0dp** [comment]
You think?

#1071 
#1056 
#1053 

Please open a new issue, and make your self known to the community

**Comment by Thomas-A-Reinert** [comment]
You´re still not answering the questions. To make it as accessible as possible for you: "_Well, you took over from Holger_. How come?" I think thats a thing that really would cover the questions of ALL US-contributors. How did you qualify for the job? We have not seen you (or your bots" for AGES

**Comment by Thomas-A-Reinert** [comment]
When you "took over the job like 3 month ago"

**Comment by 0dp** [comment]
@holger1411 
Would you care to explain?

**Comment by IanDelMar** [comment]
Obviously, UnderStrap is expanding.
https://understrap.com/blog/
https://understrap.com/overstrap/

**Comment by Thomas-A-Reinert** [comment]
Well.. Holger won´t answer anymore. According to a mail he sent me yesterday morning (..) , he dropped this project about 6 months ago. And Understrap seems to be taken over by "[Alex Booth](https://de.wordpress.org/themes/understrap/)" on Wordpress and here like THREE FRIGGING MONTH AGO.

Two days went by and he apparently didn´t feel the need to explain. Which on the other hand explains a LOT.

@IanDelMar It´s not expanding. It´s about to get commercialized. And again - we know shit about it. Do we?

**Comment by IanDelMar** [comment]
@Thomas-A-Reinert Well, I don't think, it's a big deal that it (i.e. its child themes) gets officially commercialised. I mean it has been commercialised by each person using UnderStrap or a child theme for UnderStrap for a client project. To be honest, I don't care about Holger or Alex and the rude way they were/are behaving. What I care about is:
* Is UnderStrap going to stay a free theme?
* What do commercialised child themes mean for UnderStrap? E.g., will it freeze now (as it has for the last couple of month) for the sake of the official child themes?
Etc.

But I'm waiting for the info you mentioned in #1071 to draw my final conclusions. Thanks for getting in touch with Holger and clarify some things!

**Comment by Thomas-A-Reinert** [comment]
It´s been a frigging hard day. Need to catch some hours of sleep and will try to keep you updated asap. Sorry for that.

**Comment by pattonwebz** [comment]
It is often the case that a project that the original creator no longer wants to participate it gets passed along to some else that is excited to take charge with it. That in no way detracts from the contributions that people have already offered and there is nothing forcing any one of us to continue.

I found this project through it's use of a different project that I have contributed to. The Bootstrap Navwalker one. That project is not mine, it did not get offered to me when it traded hands nor did I ever ask for it. The transfer happened to someone else and I continued working on it. I have continued to do so when I have time for like 6 or 8 years or something now.

We can all continue here to work on this in our free time or someone can fork it and continue elsewhere - perhaps take a new direction with it. I expect that this repo here will continue to be worked on a little bit here and there as people have time and/or needs. 

The Understrap theme that is released on wordpress.org will remain there forever - themes are never removed and can always be found in the SVN server https://themes.svn.wordpress.org/understrap/ Additionally that theme is still owned by @holger1411 and he has not contacted me to request it be transferred to anyone else.

While it would have been nice to have been informed there was no requirement on anyone to tell us anything. Perhaps I am not so annoyed about that as others because I am not so invested in this project. I think it's kinda nice to let a young new developer take over and see where they can take it. I would also be happy to hop along for the ride if anyone should choose to start a fork. I'm just around to contribute where I can, it bothers me not who the repo owner is :)

Welcome Alex, @UnderstrapFramework . Good luck with your plans :)

**Comment by Thomas-A-Reinert** [comment]
Please see https://github.com/understrap/understrap/issues/1071#issuecomment-563498379

**Comment by UnderstrapFramework** [comment]
Hello Everyone,

I appreciate all the work that everyone has done on UnderStrap and seems that my current approach isn’t working so let me do my best to answer the questions/comments. Also, thanks pattonwebz for the kind words in a comment 14 hours before this one :D

**Whom am I?** 

My name is Alex. I am 32 years old and live in the North of England. I am a self taught IT programmer working mainly in PHP. I have been working for 10~ years starting and building websites for myself or for clients. I first used Understrap 3 years ago and have used it several times since. As with other users, it saved me a lot of time and was a go to resource for me. I found it listed for sale on Flippa earlier this year and given my experience with UnderStrap thought it was a good resource to build a business on. I begged, borrowed and stole to raise the funds to buy it as I believe it is a major asset to the WP world. I do not have open-source community management experience and my style is a remote IT programmer, working on my own in a small bedroom office! So my apologies for not greater communication.

**What have I been doing with UnderStrap?**

My plan is to keep it free and continue in line with what Holger had done. For commits/pulls, my approach was to approve/review them on a weekly basis. Comments welcome on how to better do this process since this is a new one for me. I don’t have a handover manual or a process manual I am working off of. For the outstanding 37+ pulls, I will review those by Friday end of day, sorry for the backlog. 

Since everything I work on is related to wordpress (plugins, hosting, spamware….) I plan to build things that can integrate somehow with UnderStrap. The idea is for a user to offer a centralized portal/hub of everything WP. I have been working on UnderStrap full time and building out complementary products/services  (yes commercialisation). I have also been responding to users (emails and phone calls) who have tech questions every day, from issues to do with getting 3 level drop-downs to preparing a child theme for development.

I thought the 1 child theme on UnderStrap had very limited functionality and very low takeup. I paid a WP developer to create themes based on UnderStrap to have a broader offer than what was before (not hard there was only 1). 

**What I need help on**

If you have ideas on how to better manage UnderStrap let me know. If you have ideas on what would help users such as child themes, WP plugins let me know. I would love to hear from people either here or by private chat or through the contact form on understrap.com

If you would like to be more involved in things UnderStrap related I would love to hear from you also

**What you can expect from me**

I will try my best to respond to you guys on here and keep a better eye on things. If you see something that isn’t right please let me know publicly or privately and I will sort it ASAP

**Comment by pattonwebz** [comment]
Hello @UnderstrapFramework, welcome to the project. Also good morning, I'm also in the UK (Up in Scotland, dealing with the reason as is the norm for me here haha!).

I have some experience dealing with managing an open source project and some of the community aspects around it so feel free to message me anytime if you have questions.

As far as helping users the best advice I can give right now is to focus on child themes, in the near future a child theme type theme system will be quite likely to become the norm. UnderStrap being a good base for such themes in my view.

Looking forward to seeing your ideas come to fruition. Happy to he here and along for the ride :D

**Comment by UnderstrapFramework** [comment]
Im not that North! Sheffield area, people are friendly enough 

Iv focussed on something iv called OverStrap, which is a premium starter child theme pack with 5 flavours included..... planning on adding more soon. I figured that in the past I have wanted to speed up development but premium themes are too bulky so found a half-way

Thanks for being available for questions, I will most probably take you up at some point. Just waiting for Christmas to get out of the way and see what 2020 brings, hopefully less stress :D

**Comment by Thomas-A-Reinert** [comment]
Hey Alex / @UnderstrapFramework . 

Let me address you personally as I seem to be your nemesis with this project and you don´t seem to be willing to address ME directly even if I did before directly address YOU.

Congratulations for buying UnderStrap. Really, I mean it. If we would have had any clue that it was for SALE - well. As I already said: Holger did not communicate ***** for more than half a year. Or even more. Or from the beginning on. Or..

It´s not ALL your fault!

But from what **I know** you´ve been warned to ignore the community. And you f****ng did. For THREE months. The outcome of UnderStrap that you´re trying to market with such effort being the "_**Number 1 Bootstrap WordPress Theme**_" didn´t come from YOUR work. It was a COMMUNITY effort. Not MINE. Not Holgers. Not a SINGLE person ones. But you spit on the community in the first three month until you seen it go critical. And please don´t tell me that you didn´t notice - you got mentioned more than once. You had ENOUGH chances to communicate. Please don´t make me list ALL of those mentions, okay?

Anyway, I´m not here to demotivate you or run down your business. But let´s be honest - you fucked up the whole nine yards. There is no "_my current approach_". You had NONE and still HAVE none! You didn´t "_approach us_" at all! You´re just trying to settle down the shitstorm that´s currently going your way!

And there is no frigging excuse for not introducing yourself and pointing out a roadmap when you take over. As a freelance dev you should know that.
And even in normal life: You don´t sneak into a room and do NOT tell all of the people that their life changed until they find out. Do you? Sheffield rappers would´ve beaten my up for that in the early ninetees being their tourmanager! London and Manchester rappers would´ve probably have killed me then, but..

Anyway. It´s getting late and I spent 4-6 hours today already with this "problem" and possible solutions including personal messages, mails, forking, issue management etc. And I´m not freelancing anymore. So that goes after a 8-9hr job today.

Sorry if you got me on a well, pretty "challenging" attitude. But you´d probably understand if you went with UnderStrap for some years without feedback, putting up a documentation that never got respected/pulled which would have done lots better/helped the community/devs, managed a serious hundreds of issues etc and then THAT happens what just happened.

About the "_For the outstanding 37+ pulls, I will review those by Friday end of day, sorry for the backlog._" - don´t make any promises you can´t keep. You won´t fix em all until friday. Unless you´ll do it in a haste and compromise the whole thing therefore. And a "review" ain´t a merge, seen?
And a merge ain´t a release. And so on and on.

Communicate. And I´m sure we´ll be also willing and able to help. I´m not sure yet if that will prevent a fork for the better. "Transparency" ain´t your thing as I see it. And that would be one of the main focusses I´d put my hands on.

Have a good day and don´t be too frustrated - we don´t mean any bad to you.

Up to you to change something

**Comment by Thomas-A-Reinert** [comment]
It´s friday. Just saying. Feel free to contact me if you need help. It ain´t hard to find my site/contact me.

As I said: I´m not here to f**k up your biz. I/We, the community, just NEED/S a sign that somethings gonna change that´s been neglected for too long (6months+). As patton, ian and everyone else mentioned - we´re still here to help and really don´t wanna let understrap go. The choice is still up to you.

**Comment by UnderstrapFramework** [comment]
Hey Thomas, i'm starting to go through the pull requests now, if you see anything that doesn't look right just comment in this thread and i'l sort it ASAP, thanks

**Comment by Thomas-A-Reinert** [comment]
Hey Alex,
currently on the job and will be off over the weekend. Love to get back to you on monday if needed.

**Comment by UnderstrapFramework** [comment]
Thanks Thomas

**Comment by Thomas-A-Reinert** [comment]
Hey Alex, @UnderstrapFramework : Cool, you ALMOST complied to merge all of those merge requests! Don´t get me wrong, that one goes with a blink, because I KNEW that you couldn´t comply ;)

Affirmed: Job well done. And thanks for that. I guess you may already have noticed that since then the number of contributions raised _tremendously_ and that the "core contributors" (..)  are actually pull requesting a surprising amount compared to the past year. We ALL have a sh*tload of issues on our list that will come in now, promised. But it wasn´t any fun to contribute to a "dead" project, so ..

As I said – it´s up to you how to handle UnderStrap. But I think you got a confirmation HOW it could work out now. IF you listen to the community. 

I´m not going to handle any follow ups in THIS topic, but I think there´s a whole lot more going on and needed for the theme/community etc. I´ll mention you within any follow-up.

**Comment by Thomas-A-Reinert** [comment]
> Hey Thomas, i'm starting to go through the pull requests now, if you see anything that doesn't look right just comment in this thread and i'l sort it ASAP, thanks

Really didn´t have any quality check at all - there was just too many merges. Sorry. That´s the problem with having so many of them.

1. I didn´t do any 'npm install'
2. I didn´t really quality chek anything at all
3. I just checked and confirmed HTML - and that´s about it

If you got any requests on what to test exactly - let me know. Can/Won´t promise anything but will take that into focus.

**Comment by UnderstrapFramework** [comment]
Whatever you feel is most important Thomas, NPM is not my strong point though

Mentioning me is really helpful so I can see it in my emails and respond ASAP

**Comment by Thomas-A-Reinert** [comment]
First of all: Wish you a happy christmas, @UnderstrapFramework !
Second: If you ain´t got a clue bout anything and don´t feel that you can quality check it - DO NO MERGE IT! EVERY merge request should be tested in a dev-environment before getting merged. Remember? That´s why I said that you´ll never be able to fulfill all those merge requests til friday, as I said before: https://github.com/understrap/understrap/issues/1071 "**Don´t merge anything untested, without speaking to people who might have already tested and/or commented.**". Well.

Really, it´s not my job to fuck you up. But you´re really, really NOT listening to people that REALLY want to help you. Get the base of your "software" to work first and THEN care about every fucking bullsh*`t second. And I also guess that once you got problem A.) solved we´re ALL willing to help you with problem B.)

**Comment by IanDelMar** [comment]
@Thomas-A-Reinert I hope not one of my PRs was causing your x-mas anger. I wish you a merry christmas, too

**Comment by Thomas-A-Reinert** [comment]
:) No, don´t worry. Didn´t even check em. And there´s no such thing as "_x-mas anger_". I´m cool. Really. First day since a quarter where I can do what I want and focus on what I want though. Just trying to work up a bit of what aggregated over the past few days.

**Pull request merged**
