### PR TITLE
Fix HTML comments

### PR DESCRIPTION
**Pull request by IanDelMar**
## Description
This PR
* removes redundant HTML comments.
* hides comments not meant for public display.
* fixes classes/ids in HTML comments.

## Motivation and Context
* Declutter HTML output.
* Use correct comments.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

None of these.

## Checklist:

- [x] I pulled my branch from `develop`.
- [x] I am submitting my pull request to `develop`.
- [x] I have resolved any conflicts merging this pull request would create.
- [x] I have checked that there aren't other open Pull Requests for the same update/change.
- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] \(Optional) My change requires a change to the documentation.
- [ ] \(Optional) I have updated the documentation accordingly.
- [ ] \(Optional) My change requires a change to the translations.
- [ ] \(Optional) I have updated the translations accordingly.
- [x] `composer cs:check` has passed locally.
- [x] `composer lint:php` has passed locally.
- [x] I have read the **[CONTRIBUTING](https://github.com/understrap/understrap/blob/main/.github/CONTRIBUTING.md)** document.

## Related Issues or Roadmap requests
None.

## Further comments
It would be good to have a discussion whether the comments are needed at all. I think most people do not look at the HTML page source but use some sort of code inspection tool to look at the HTML.

### CODE REVIEW

**Comment by bacoords** [comment]
Yeah overall these are really good updates. There's a lot of HTML comments that should've actually been PHP comments, which you've tackled. I'll do a deeper review, but I'm in favor of these changes.

I'm also not a fan of general HTML comments on closing tags, but I would leave that open to discussion and probably lean towards leaving them if they're useful for newer developers.

**Comment by bacoords** [comment]
How do you feel about the ones like this: `<!-- ******************* The Navbar Area ******************* -->`?

I see them in `header.php` and the sidebar-templates. Feels like not the best way to do it or to at least do them as PHP comments but wondering what you think here?

**Comment by IanDelMar** [comment]
I'd remove _all_ HTML comments. None of them, not the "area comments" and not the closing tag comments are consistently placed throughout the templates. While we could comment all the different areas, there's no way to add closing tag comments in HTML generated by WP functions.

**Comment by IanDelMar** [comment]
@bacoords Is there a final decision on "area comments" and the closing tag comments?

**Review by bacoords — APPROVED** [review]

**Pull request merged**
