### PR TITLE
Use issue template chooser

### PR DESCRIPTION
**Pull request by IanDelMar**
## Description

This PR replaces the issue template with the issue template chooser. It creates 3 issue types to choose from:
- bug report
- support request
- question

The template chooser is configured to offer the option to open a blank issue.

## Motivation and Context

The issue template chooser allows to select the type of issue and pulls different issue templates accordingly. Each template is configured to assign the corresponding label to the issue automatically.

## Types of changes

Does not affect production code or build system.

## Checklist:

- [x] I have checked that there aren't other open Pull Requests for the same update/change.
- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] \(Optional) My change requires a change to the documentation.
- [ ] \(Optional) I have updated the documentation accordingly.
- [ ] \(Optional) My change requires a change to the translations.
- [ ] \(Optional) I have updated the translations accordingly.
- [x] `composer cs:check` has passed locally.
- [x] `composer lint:php` has passed locally.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by danemorgan** [comment]
I'm thinking we might do better to keep the issues section limited to bugs and support requests and direct "Ask a Question" responses to the Discussion area, where we have a specific Questions board. 

I'm not sure if it's possible to do that with a template, or if we have to just link to it?

**Comment by IanDelMar** [comment]
I wasn't aware of this. Shame on me. But I was so pissed of by former UnderstrapFramework I unwatched Understrap. I'll have a look at it.

**Comment by IanDelMar** [comment]
@danemorgan is this what you were thinking of?

**Comment by danemorgan** [comment]
@IanDelMar I belive it is, sir.

**Review by danemorgan — APPROVED** [review]

**Pull request merged**
