### PR TITLE
Reworking of gulpfile and a few others to be more organized

### PR DESCRIPTION
**Pull request by AustinBurns**
Hello,

I recently used Understrap for a project and found out that while I like it a lot, the Gulpfile needed a LOT of love as well as the organization of asset files.

First, I took all asset files and put them under a directory called 'static' so that it is easy to know where all asset files live plus there is less clutter in the top level directory.

Second, I removed NPM packages that either weren't being used or were outdated/duplicates and added ones that either worked, or did the job better. I also streamlined the way the gulpfile works with copying assets, running sass, minifying js/css, and then running watch. There is also a default gulp task now that runs everything if need be.

Third, I reworked the way the sass directories/files are brought into the theme.scss so that there is a lot more organization of theme sass files. I did the same to the JS files/directories.

Lastly, I did a few other miscellaneous changes like adding a better .gitignore, changing the directory 'global-templates' to 'modules' to be in line with the sass 'modules' directory and added one or two more optional NPM packages that I think work great for a lot of themes(obviously they can just be commented out/deleted in the gulpfile if not needed for a certain project).

Let me know if there is anything you would like me to change or fix.

Thanks,

Austin

### CODE REVIEW

**Comment by raisonon** [comment]
I'm also keen to re-work the gulp file and have done so on my own installs.

Perhaps if you were to submit these pull requests as multiple items it would be easier to separate and work on individual tickets and get added to core. Ta

**Comment by AustinBurns** [comment]
@holger1411, would you be ok with what @raisonon mentioned about putting the working into multiple pull requests and submitting them so that you can add them into core easier? Or are you not looking to add my changes in? If not, no worries, just wanting to know if that is something you are interesting in before I go through the trouble of getting that worked out.

**Comment by holger1411** [comment]
Basically yes, but it seems there are various merge conflicts.
If you create single and smaller pull requests its much easier to review and to merge - But nevertheless: Thx!

**Comment by AustinBurns** [comment]
Well yes, there are conflicts now as this Pull Request was originally made a few months ago. At the time of making this PR, it was clean, but I never heard any feedback from you so I didn't keep up with it.

Now that I know though, I will go back and pull the latest master, fix all conflicts and start to make a bunch of small Pull Requests :)

Thanks!

**Comment by holger1411** [comment]
Argh, sorry!

**Comment by VesterDe** [comment]
And thanks :)
ᐧ

------------------------------------------------------------------------
Demjan Vester: LINKED-IN <http://si.linkedin.com/in/vesterde/>
Phone: +386 (0)40 193 536

**Comment by AustinBurns** [comment]
Haha no problem at all :) Should start making the PRs by the end of this weekend :)

**Comment by holger1411** [comment]
Closing this because it is outdated. Sorry!

**Pull request closed without merging**
