### PR TITLE
Create Japanese translation

### PR DESCRIPTION
**Pull request by teruteru128**
I created Japanese translation.
I hope you will accept this pull request.

### CODE REVIEW

**Comment by Thomas-A-Reinert** [comment]
I wish I´d be able to quality-check the translation.. but I don´t speak japanese ;) 
So would normally accept the translation, because anyone else could build up on that and/or improve it, but i gotta deny it anyway.

Reason: We cannot accept translations with just the .mo file included. We need the (editable) .po file too for others to update/improve. Please supply that too and submit another pull request with both files, okay?

Thanks for your effort!

**Comment by teruteru128** [comment]
Excuse me?
This Pull Request contains a .po file. Please check again.

**Comment by Thomas-A-Reinert** [comment]
Sorry, my bad - can´t explain how I missed that.. :/

**Comment by 0dp** [comment]
AZS 👍

**Pull request merged**
