### PR TITLE
Fix search block widget

### LINKED ISSUE #1533: searchform.php doesn't seem to override the new gutenberg-based search widget
The search widget that shows up now as a block instead of the old widget doesn't get the correct button/input styling

### PR DESCRIPTION
**Pull request by IanDelMar**
## Description

This PR
* uses a filter to add Bootstrap classes to the search form.
* fixes the button position styles.
* fixes the label styles.

## Motivation and Context

#1647 tried to fix #1533. However, it added a lot of CSS, makes  `<label>` permanently invisible and introduced unexpected styles.

### Reduction of CSS file size
* theme-bootstrap4.css: from 570 KB to 368 KB.
* theme-bootstrap4.min.css: from 488 KB to 313 KB.
* theme.css: from 418 KB to 334 KB.
* theme.min.css: from 349 KB to 281 KB.

#### Before this PR
image
#### After this PR
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I pulled my branch from `develop`.
- [x] I am submitting my pull request to `develop`.
- [x] I have resolved any conflicts merging this pull request would create.
- [x] I have checked that there aren't other open Pull Requests for the same update/change.
- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] \(Optional) My change requires a change to the documentation.
- [ ] \(Optional) I have updated the documentation accordingly.
- [ ] \(Optional) My change requires a change to the translations.
- [ ] \(Optional) I have updated the translations accordingly.
- [x] `composer cs:check` has passed locally.
- [x] `composer lint:php` has passed locally.
- [x] I have read the **[CONTRIBUTING](https://github.com/understrap/understrap/blob/main/.github/CONTRIBUTING.md)** document.

## Related Issues or Roadmap requests
Related to #1647
Fixes #1533

### CODE REVIEW

**Comment by IanDelMar** [comment]
@bacoords this PR needs a review.

**Comment by bacoords** [comment]
Great @IanDelMar  - I'm going to pull in the latest BS version from #1821 and then test all the style fixes

**Comment by IanDelMar** [comment]
@bacoords I'll resolve the conflicts that will then occur.

**Comment by IanDelMar** [comment]
@bacoords I resolved the conflicts and updated the PHPStan baseline. I'll work on the "no value type specified in iterable" errors at some point in the future.

**Comment by bacoords** [comment]
This is great- I'd never even played with the new search widget. I thought only the 'legacy' search widget was available.

**Review by bacoords — APPROVED** [review]

**Pull request merged**
