### PR TITLE
Gulp4

### PR DESCRIPTION
**Pull request by vedderman**

### CODE REVIEW

**Comment by Mte90** [comment]
any updates for this?

**Comment by 0dp** [comment]
Hi @Mte90 

Yeah, check out PR #883 

Still waiting for feedback from @holger1411 et al.

I would very much appreciate if you could take it for a spin and report back.

You can download the fork here:
https://github.com/0dp/understrap/tree/master

Documentation is found in #883

**Comment by 0dp** [comment]
@holger1411 can you close this, this is stale

**Comment by axlright** [comment]
@0dp I must have been hibernating. Why is this stale?

**Comment by 0dp** [comment]
Because I created a much more efficient and version called gulp4 new and improved.

**Comment by 0dp** [comment]
PS. Another contributor proposed a gulp4 flow that was much more of the likens of Holger. And it has already been merged into master

**Pull request closed without merging**
