### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by IanDelMar**
- Uses more generic patterns
- Adds some editor files
- Adds some always-ignore extensions

Comments very welcome!

### CODE REVIEW

**Comment by IanDelMar** [comment]
@UnderstrapFramework please merge

**Comment by IanDelMar** [comment]
@UnderstrapFramework still here?

**Comment by IanDelMar** [comment]
@UnderstrapFramework ?

**Comment by UnderstrapFramework** [comment]
Thanks

**Comment by Thomas-A-Reinert** [comment]
10 merges within 3 minutes. It´s evident that no code-review has been done.
I´ll leave any interpretations open to the users of UnderStrap.

**Pull request merged**
