### PR TITLE
Update dependencies incl. Bootstrap

### PR DESCRIPTION
**Pull request by IanDelMar**
- Bumps autoprefixer from 9.7.6 to 9.8.0
- Bumps bootstrap from 4.4.1 to 4.5.0 
- Bumps @babel/core from 7.9.0 to 7.9.6
- Bumps @babel/preset-env from 7.9.5 to 7.9.6
- Bumps gulp-imagemin from 5.0.3 to 7.1.0
- Bumps del from 4.1.1 to 5.1.0
- Bumps gulp-rename from 1.4.0 to 2.0.0

### CODE REVIEW

**Comment by IanDelMar** [comment]
@UnderstrapFramework please merge

**Comment by pattonwebz** [comment]
:+1: Works for me :)

**Comment by IanDelMar** [comment]
> @UnderstrapFramework please merge

@UnderstrapFramework ?

**Comment by UnderstrapFramework** [comment]
Thanks @IanDelMar

**Pull request merged**
