### PR TITLE
Update bootstrap and other dependencies

### LINKED ISSUE #1213: Lodash - Github security alert!
Hey there.

Just want to let you know, Github gave me this security issue:

Vulnerable versions: < 4.17.19
Patched version: 4.17.19
Versions of lodash prior to 4.17.19 are vulnerable to Prototype Pollution. The function zipObjectDeep allows a malicious user to modify the prototype of Object if the property identifiers are user-supplied. Being affected by this issue requires zipping objects based on user-provided property arrays.

This vulnerability causes the addition or modification of an existing property that will exist on all objects and may lead to Denial of Service or Code Execution under specific circumstances.

Thanks.

### PR DESCRIPTION
**Pull request by IanDelMar**
## Description
Bumps
- [bootstrap](https://github.com/twbs/bootstrap) from 4.5.0 to 4.5.3
- [@babel/preset-env](https://github.com/babel/babel/tree/HEAD/packages/babel-preset-env) from 7.10.2 to 7.11.5
- [@babel/core](https://github.com/babel/babel/tree/HEAD/packages/babel-core) from 7.10.2 to 7.11.6
- [phpcodesniffer-composer-installer](https://github.com/Dealerdirect/phpcodesniffer-composer-installer) from 0.6.2 to 0.7.0
- [autoprefixer](https://github.com/postcss/autoprefixer) from 9.8.0 to 9.8.6
- [browser-sync](https://github.com/BrowserSync/browser-sync) from 2.26.7 to 2.26.12
- [lodash](https://github.com/lodash/lodash) from 4.17.15 to 4.17.19
- [gulp-cli](https://github.com/gulpjs/gulp-cli) from 2.2.1 to 2.3.0
- [php_codesniffer](https://github.com/squizlabs/PHP_CodeSniffer) from 3.5.5 to 3.5.6
- [del](https://github.com/sindresorhus/del) from 5.0.1 to 6.0.0

Fixes #1213.

### CODE REVIEW

**Comment by IanDelMar** [comment]
@UnderstrapFramework please merge

**Comment by IanDelMar** [comment]
@UnderstrapFramework please merge

**Comment by IanDelMar** [comment]
@UnderstrapFramework please merge

**Comment by IanDelMar** [comment]
@UnderstrapFramework are you still alive? Please merge!

**Comment by UnderstrapFramework** [comment]
Thanks

**Comment by Thomas-A-Reinert** [comment]
10 merges within 3 minutes. It´s evident that no code-review has been done.
I´ll leave any interpretations open to the users of UnderStrap.

**Pull request merged**
