### PR TITLE
Woocommerce 3.6.1 updates

### PR DESCRIPTION
**Pull request by chrismb75**

### CODE REVIEW

**Comment by noelspringer** [comment]
**Questions:**

1. Is the initial commit 89f2509 (`gulpconfig.json`) a part of the Woocommerce template updates?
2. `global/quantity-input.php` - the 3.6.0 version removes the `aria-labelledby` attribute from the input element - line 45 in version 3.4.0. Should that be retained?

As:

`aria-labelledby="<?php echo esc_attr( $label ); ?>"`

**Comment by chrismb75** [comment]
Hi Noel.

1. No. Apologies, that was my mistake.
2. Not according to this commit here https://github.com/woocommerce/woocommerce/commit/5f0eb2d31255bda208118a0b268b91374a2b78e

**Comment by noelspringer** [comment]
Thanks Chris!

Regarding the ARIA attribute, thanks for the link. I see that it was removed from upstream but I was more curious as to why an accessibiity attribute was removed.

**Comment by noelspringer** [comment]
BTW Chris before I noticed your pull request I had opened an issue/question regarding `single-product/rating.php` #956.

I would be interested in your view on that question.

Cheers

**Comment by chrismb75** [comment]
Hi Noel,
         RE aria labelledby the discussion here explains it. https://github.com/woocommerce/woocommerce/pull/23186

**Comment by noelspringer** [comment]
Hi Chris Thanks for the link.

**Comment by noelspringer** [comment]
Hi Chris,  I noticed your branch has conflicts now.

**Comment by chrismb75** [comment]
Hi Noel,
             I am a little confused, perhaps @holger1411  can shed some light on this. The commits here https://github.com/understrap/understrap/commit/cac4962ddb057f8dc73f139f94c442e455798df7 do not match upstream Woocommerce changes?

**Comment by noelspringer** [comment]
Hi Chris,

I was wondering how the conflict arose. Now I see. 

To be precise there are no template changes in 3.6.1. Any changes that were made were done for 3.6.0. And the files affected are only the six  you addressed.

Looking at cac4962 I can see that Woocommerce code changes haven't been incorporated. So yes I am puzzled also. @holger1411

**Pull request merged**
