### PR TITLE
Swap customized walker to latest upstream wp-bootstrap-navwalker class

### PR DESCRIPTION
**Pull request by pattonwebz**
Use upstream navwalker in the theme. Ref #632

### CODE REVIEW

**Comment by pattonwebz** [comment]
@Thomas-A-Reinert updated this PR. Should be working correctly now. I pushed it from my working directory this time like I should have done previously.

Note: `Understrap` is prefixed on the class name with an uppercase `U` You can change it to lowercase if you want so it matches the previous usage exactly but class names are not case sensitive so should work both ways :) This PR also adds 2 additional strings (with the text domain of `understrap`) in the fallback function that could need translated.

**Comment by axlright** [comment]
Thanks @pattonwebz for your contribution 🚀

**Comment by axlright** [comment]
@Thomas-A-Reinert I'm happy to help test in a demo environment if you can give me an outline of what to test. I'm kinda dumb about nav walkers, but I'd like to learn.

**Comment by 0dp** [comment]
> Thanks @pattonwebz for your contribution 🚀

EMOJIIIIIIII

**Comment by Thomas-A-Reinert** [comment]
Works like a charm now and also keeps child-themes working after update!

Lesson learned: 

> PHP-functions are not case-sensitive

 ;)

Thanks again @pattonwebz !

**Pull request merged**
