### PR TITLE
Adjust styling of issue templates

### PR DESCRIPTION
**Pull request by IanDelMar**
## Description
This PR adds headings instead of bold text for sectioning.

## Motivation and Context
I have used the new issue template (#1349) and one gets lost because there is no structure at first sight.

## Types of changes
No changes to production code or build system

### CODE REVIEW

**Comment by Thomas-A-Reinert** [comment]
Is this PR actually trying to solve any a11y-problems? that would be nice in fact.
If not - give a sh*t about hierarchy. It should be usable, nothing more, nothing less.

I can actually test it, as soon as there is a test-deployment avail.
HINT: @danemorgan @bacoords etc. – it would be really helpful to have some test-staging before PR/MR´s get merged to the main branch. To assure a11y compliance, i need to have a working example.

**Comment by pattonwebz** [comment]
@Thomas-A-Reinert A summary of the changes here are that the headings from the issue template are all updated to use H2s where as previously they skipped levels and used bold text to imply headings.

Now when someone creates an issue using the template the main issue title is an H1 tag (as always) and the headlines from the template use H2s.

The file is in markdown and gets generated HTML from it, you can see a working example of the output this change generates here: https://github.com/understrap/understrap/blob/2c9c38c78c87b3de288400c9542370a644d4847e/.github/ISSUE_TEMPLATE/1-bug-report.md

**Comment by Thomas-A-Reinert** [comment]
@pattonwebz - thanks. I didn´t need an accessibility explanation. I just needed a valid preview to TEST.

**NOTE: PLEASE! Install the https://github.com/dzc34/headingsMap Plugin for your fav browser. That and bunch of bookmarklets solve about 85% of all problems!**

So... 
image

In MY eyes this looks super-f*cking pretty sh*tty,
- What is that understrap/understrap &lt;H1>? . I guess you cannot change that, but it´s super-un-intuitive for any blind user, I guess? Sidenote: I heard MS is working on that. No promises though.
- "_understrap/.github/ISSUE_TEMPLATE/1-bug-report.md_" do I need to say more? Without a prefix like "Issue" or whatever that doesn´t make any sense for any non-sighted user.
- everything being on the same hierarchy-level.. well. not good. Hierarchy COULD be improved at least. And be it by introducing new h2 that characterize the following h3´s


image

**Comment by howarddc** [comment]
@Thomas-A-Reinert 

Please use professional language and treat your fellow contributors with kindness and respect. 

This is your second warning. If you use profanity or are rude to others in this community again, I will ban you. While I appreciate your contributions, maintaining a healthy and professional atmosphere is non-negotiable.

**Comment by Thomas-A-Reinert** [comment]
Okay, so I'm asking again. Where/in which case I did not comply. You're
still not giving answers just accusations.

Rob Howard ***@***.***> schrieb am Sa., 31. Juli 2021, 00:47:

**Comment by Thomas-A-Reinert** [comment]
Where was the first warning?

Thomas A. Reinert ***@***.***> schrieb am Sa., 31. Juli 2021,
00:55:

**Comment by Thomas-A-Reinert** [comment]
Wherever have I been really rude?
So far you're not giving any answer at all. You're just trying to blame me
for no followable reason or am I missing out on anything?!

Thomas A. Reinert ***@***.***> schrieb am Sa., 31. Juli 2021,
00:56:

**Comment by howarddc** [comment]
@Thomas-A-Reinert 

You used profanity in #1349 twice, once before I posted about it on #1350, and once after.

In order to continue contributing, you must behave professionally here at all times, applying the same standard you would in a workplace or other public setting. This includes not using profanity and being respectful to your fellow contributors.

**Comment by danemorgan** [comment]
@Thomas-A-Reinert HINT: there is a develop branch that has current development. Feel free to pull it and use it all you want. That's what will be merged to main when the time is right.

**Comment by Thomas-A-Reinert** [comment]
@howarddc sorry, still cannot detect any profanity. We can spend a week or two isolating the problem or you can just QUOTE it. By code or content.
Aside from any no-blaming, no-whatever-policy or whatever may ride you: I BEG YOU TO TELL ME EXACTLY!

**Comment by howarddc** [comment]
Hi all,

I've removed Thomas from the repository and disabled his access to the Understrap organization's repos and discussions. As I mentioned, I want to establish firm communication guidelines throughout this community, including no profanity, rudeness, verbal attacks, etc., and in my judgement Thomas was repeatedly behaving unprofessionally here.

At the same time, I know there is always some gray area in these decisions. I am open to your thoughts on the best way to document clear, firm and fair communication standards - feel free to reach out to me at rob@howarddc.com with ideas (or we can start a new public discussion thread on that). I want to ensure everyone is free to speak their mind - and I disagreed with and reversed the previous owner's decision to ban people. However, it's crucial that we make this a universally positive and welcoming place - this should be fun, and I don't think there's any place for ad hominem attacks, sarcasm, mockery or cursing in the work we're doing.

Anyone who is removed as a result of violating our communication standards can request readmission after 30 days by e-mailing a request to support@understrap.com 👍 

Please don't hesitate to reach out if you have any questions, and thank you all for being a part of Understrap!

**Comment by IanDelMar** [comment]
> @Thomas-A-Reinert HINT: there is a develop branch that has current development. Feel free to pull it and use it all you want. That's what will be merged to main when the time is right.

@danemorgan I think @Thomas-A-Reinert was walking about the issue template which actually did get merged into the main branch because we wanted people to be able to use it.

**Comment by IanDelMar** [comment]
@Thomas-A-Reinert the preview doesn't matter because usually nobody gets there.

I had a look at two scenarios now:
1. Opening a new issue.
   * We have an h1 with the repo name and an h2 with "Issue: bug report" or "Issue: feature request".
image
   * I made almost all the comments directing people through the issue (\\) being normal text. Screen readers will read "<!--".
2. Reading an old issue.
Not surprising given the headings from opening a new issue it's best to have h3 headings for structuring the issue.
image
   * We cannot change understrap/understap (h1)
   * We cannot change the second h1 which is the titel of the issue.
   * We cannot change the "Comment" h2 which is the heading of the issue body including the comments.
   * Then there are a couple of h3 headings. The fist h3 indicates that I edited the issue and cannot be changed. The following h3 headings are those used in the bug report. The last h3 is the first comment on the bug report.

I think that's the most we can do about the issue templates. Any thoughts on this from anyone?

I'm afraid the [issue template chooser](https://github.com/understrap/understrap/issues/new/choose) itself is not accessible at all. There's nothing we can do about it except for dropping it again.

**Review by danemorgan — APPROVED** [review]

**Pull request merged**
