### PR TITLE
RTL styles using gulp-rtlcss plugin

### PR DESCRIPTION
**Pull request by Milimas**
Gulp plugin that uses RTLCSS to convert LTR CSS to RTL instead of changing css manually.
feel free to correct my english

## Description

using gulp-rtlcss plugin instead of editing css or adding rtl.css file.

## Motivation and Context

this plugin make it easier to change sass files and distribute rtl css files just by saving sass file while running `$ glup watch` command

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have checked that there aren't other open Pull Requests for the same update/change.
- [ ] My code follows the code style of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] \(Optional) My change requires a change to the documentation.
- [x] \(Optional) I have updated the documentation accordingly.
- [ ] \(Optional) My change requires a change to the translations.
- [ ] \(Optional) I have updated the translations accordingly.
- [ ] `composer cs:check` has passed locally.
- [ ] `composer lint:php` has passed locally.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by danemorgan** [comment]
Thanks @Milimas,

This PR does not actually include the RTL plugin in the gulpfile, instead it provides instructions for doing so in the readme. I'm in favor of approving this commit. It's in keeping with only building in things that a majority of users are going to need, but at the same time making them more accessible for those who might.

@bacoords, we might want to also adopt, and expand on this for our documentation project. As well as looking for other helpful plugins that might not be right for including, but that we can point people in the right directions.

**Comment by bacoords** [comment]
@danemorgan Have we tested this method? I know we're just recommending it but not installing it (which makes sense to me) but I think we should test it out first.

I'd also be open to keeping both in the readme (and eventually documentation), the original/easy WordPress method and the more 'advanced' method as outlined here.

**Comment by danemorgan** [comment]
@bacoords I agree. I have not merged it yet because I have not tested it to make sure it works.

Also, I want to see what you think of adding integrations.md, or scripts.md, or build.md file to collect these kinds of things in with a link from the readme.md.

**Comment by bacoords** [comment]
As we're moving away from Gulp on the develop branch, I'm closing the PR. However, I HIGHLY encourage the original author to look into adding RTL support for the next release. We're using the same build process as Bootstrap and I know they have a lot of built in RTL stuff there.

**Pull request closed without merging**
